# Generated by Django 4.2.3 on 2023-07-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_first_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='batch_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
